### ISSUE TITLE
Documentation Roadmap Discussion

### ISSUE THREAD

**Issue by Alex-Monahan** [duckdb/duckdb-web#117]
I wanted to build a central list of documentation tasks in order to prioritize them. I've tied in existing issues where applicable. Feedback is welcome! Please let me know what I forgot or if the order of importance should be changed. 

Tactical items:
- [x] Add list arguments to parquet documentation 
- [x] Enhance nested types documentation (#110)
- [x] Document the filter clause 
- [x] Interval Data Type (#137)
- [x] Revisit benchmarks (#78)
- [x] Document the new extension installation feature
- [x] Generate a single PDF for each commit (#964)
- [x] Document remaining undocumented functions that DuckDB already supports (duckdb/duckdb#2729 and related to #108 )
- [ ] Document transferring to/from different RDBMS systems (#113)
- [ ] Enhance compilation documentation (I've got some help needed here as I've only used Windows and haven't compiled DuckDB just yet!)
- [ ] Document using configuration options in Python connection
- [ ] Document compression options
- [ ] Link to existing blog posts in relevant locations in the docs

Walkthroughs / tutorials (These could be blog posts maybe?)
- [x] Using various IDE's with DuckDB (DBeaver, Jupyter Lab SQL?, SQLite IDE's?)
- [ ] Integrate with additional Python data tools (Dask, Modin, Vaex)
- [ ] Integrate with Python orchestrators (Prefect, Dagster, Airflow)
        This can be a small or large effort. We could just do a demo, or integrate directly ([Prefect has the ability to build custom connectors](https://docs.prefect.io/core/task_library/overview.html) and has Postgres and SQLite already.)
- [ ] Integrate with visualization engines (Redash, Metabase, Apache Superset). These likely require building small connectors for each library
- [ ] Getting started with DuckDB for folks coming from a purely SQL background (Ex: PostgreSQL or SQL Server)

Larger items:
- [x] Integrate DuckDB WASM documentation in some way (Basic installation steps / simple example? Or just link to the other repo?) 
       duckdb/duckdb-wasm#438
       duckdb/duckdb-wasm#375
- [x] Document the node.js Client API (#138) (This may be easier for me than the others since I've used it a little more, so I put it first)
- [x] Document the CLI (#125)
- [ ] Document the Python Relational API (Is this likely to change much or is it ok to document now?)
- [ ] Add examples for trickier functions, especially aggregates, etc.
- [ ] Build user-editable examples using DuckDB WASM 
        Ex: Interactive SQL IDE that can be pre-populated with examples from docs

**Comment by Mytherin** [comment]
Thanks for the extensive list! Looks great to me.

Some notes:

> Document the Python Relational API (Is this likely to change much or is it ok to document now?)

@pdet will likely make some changes there soon-ish, so let's hold off on that for the time being.

> Add versioning to the docs

Our web designers are working on adding this. The current idea is to always work on the main documentation (`docs`), and when a version is released we copy the current documentation to a subfolder (e.g. `docs/archive/0.3.2`). Any page that you open in the docs will include links to the older (archived) documentation for that page for older versions (if any), and display the first version for which this documentation page was created.

**Comment by pdet** [comment]
@Mytherin I assume we will  mostly add new functions, but I think we should still document what we already have there, no?

**Comment by Mytherin** [comment]
> @Mytherin I assume we will mostly add new functions, but I think we should still document what we already have there, no?

Fair enough, we can indeed start documenting what's there then already.

**Comment by Mytherin** [comment]
Another item to add to the list: as @samansmink adds more compression functions we will want to document those as well (and write a blog post about them of course!).

**Comment by darthf1** [comment]
A minor one:

https://duckdb.org/docs/data/parquet#multi-file-reads-and-globs discusses the glob syntax but not the list syntax added in https://github.com/duckdb/duckdb/pull/1945.

**Comment by Alex-Monahan** [comment]
While documenting the nested functions, I found that there is not a list_slice function. Would you folks be open to adding that as an alias for array_slice? I don't believe that other systems implement it, but it would make our naming more consistent and would prevent a user from needing to use any functions named "array_" (since they would all have aliases).

**Comment by Alex-Monahan** [comment]
For documenting the FILTER clause, I feel like it should appear in several of the different railroad syntax diagrams. Here's my guess as to where it should be included:
1. Its own individual diagram
2. Aggregates
3. Window Functions
4. SELECT diagram overall

Thoughts? 

Any other feedback on the Filter clause as I get started? Thanks!

**Comment by Mause** [comment]
Might be worth using the projects feature in GitHub to manage this list? Or at least pinning this card

**Comment by rpbouman** [comment]
Hi all. Would there be any interest in a section documenting all of the `duckdb_` table functions? 

Superficially they may be 'just functions', but they behave just like the data dictionary (like `sys` tables in MS SQL, or the `information_schema` in standard SQL). For that reason, I would expect to see them in a section at the same level as the information_schema.

Initially, it could just be one page documenting their name, a brief description of its purpoose and a listing of their result columns, later it could be expanded into separate pages with examples (if necessary).

If you like this idea, I can work on it for a bit and send a PR so you can take a look.

Sound good?

**Comment by Alex-Monahan** [comment]
That sounds excellent! Thank you!

If it comes in handy, `select * from duckdb_functions()` should get you a full list that you can filter down!

**Comment by rpbouman** [comment]
@Alex-Monahan hi! Just sent a PR. https://github.com/duckdb/duckdb-web/pull/446 Let me know it that's ok. Cheers!

**Comment by hannes** [comment]
pretty old this
